name: Test VoiceOver

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-voiceover:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Guidepup Setup
        uses: guidepup/setup-action@0.7.0
      - run: yarn install --frozen-lockfile
      - run: yarn pretest
      - run: yarn test:${{ matrix.browser }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifacts
          path: ./test-results/**/*